atabases:
  - name: Bizz-app
    databaseName: biz_app_development
    user: postgres

services:
  - type: web
    name: Bizz-app
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Bizz-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
